/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 finan.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/finan.glb')
  return (
    <group {...props} dispose={null}>
      <group />
    </group>
  )
}

useGLTF.preload('/finan.glb')
