/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("../../assets/animation/Banking.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Circle"
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials.a2}
          scale={4.029}
        />
        <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.004"]}
          position={[0, 0.946, 0]}
          rotation={[0, 0, -Math.PI]}
        >
          <group name="Circle001" position={[0, -1.022, 0]} scale={4.061}>
            <mesh
              name="Circle001_1"
              castShadow
              receiveShadow
              geometry={nodes.Circle001_1.geometry}
              material={materials["final.002"]}
            />
            <mesh
              name="Circle001_2"
              castShadow
              receiveShadow
              geometry={nodes.Circle001_2.geometry}
              material={materials["Material.003"]}
            />
            <mesh
              name="Plane011"
              castShadow
              receiveShadow
              geometry={nodes.Plane011.geometry}
              material={materials["final.002"]}
              position={[0.016, 0.205, -0.012]}
              rotation={[0.287, 1.552, 2.854]}
              scale={0.249}
            >
              <mesh
                name="Plane007"
                castShadow
                receiveShadow
                geometry={nodes.Plane007.geometry}
                material={materials["final.002"]}
                position={[0.024, 1.467, -0.196]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.37}
              >
                <mesh
                  name="Plane010"
                  castShadow
                  receiveShadow
                  geometry={nodes.Plane010.geometry}
                  material={materials.a2}
                  position={[0.501, 0.19, 0]}
                >
                  <mesh
                    name="Circle005"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle005.geometry}
                    material={materials.m11}
                    position={[-0.489, 0.01, 0.009]}
                    scale={0.165}
                  />
                </mesh>
              </mesh>
              <mesh
                name="Plane016"
                castShadow
                receiveShadow
                geometry={nodes.Plane016.geometry}
                material={materials.Material}
                position={[0.024, 1.467, -0.196]}
                rotation={[Math.PI / 2, 0, 0]}
                scale={1.37}
              />
            </mesh>
          </group>
        </mesh>
        <mesh
          name="Plane"
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials.final}
          position={[0, 0.897, -2.981]}
        />
        <mesh
          name="Plane001"
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials.final}
          position={[0, 0.897, 3.169]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("../../assets/animation/Banking.glb");
